const projects = [
  { title: "California Home Price Prediction", date: "In progress", type: "IDXExchange internship · Machine learning", preview: "property", link: "https://github.com/sammydyx/IDXExchange-Data-Science", copy: "A California single-family home valuation model built from historical CRMLS transactions. The project engineers non-leaky property, location, school-district, and amenity features to predict final sale prices and compare regression models.", tags: ["Python", "scikit-learn", "XGBoost", "LightGBM", "Feature Engineering", "Model Evaluation"] },
  { title: "Real-Time AI Agent Monitoring Dashboard", date: "In progress", type: "LLM observability · Data platform", preview: "agent", link: "https://github.com/sammydyx/Real-Time-AI-Agent-Monitoring-Dashboard", copy: "An LLM observability platform that records AI-agent runs, steps, and model calls, combining reliable event ingestion, version-aware cost tracking, historical analytics, and live monitoring in one dashboard.", tags: ["Python", "FastAPI", "Redis Streams", "DuckDB", "dbt", "React", "Recharts", "WebSocket"] },
  { title: "Pockit App", date: "Jul 2026", type: "Product design · Full-stack web", image: "/projects/pockit.png", link: "https://github.com/keemothy/Pockit", copy: "A personal-finance platform for young adults, bringing subscriptions, credit cards, spending insights, and upcoming payments into one dashboard.", tags: ["Figma", "TypeScript", "React", "Next.js", "HTML/CSS", "Supabase/PostgreSQL", "UI/UX Design"] },
  { title: "Quantitative Wheel Strategy Backtesting", date: "May 2026", type: "Python · Quantitative finance", image: "/projects/wheel.png", link: "https://github.com/sammydyx/quant-wheel-strategy-backtest", copy: "A Python backtesting framework that compares an options Wheel Strategy with a passive SPY buy-and-hold benchmark.", tags: ["Python", "pandas", "NumPy", "yfinance", "Matplotlib"] },
  { title: "Build Your Own World", date: "Apr 2026", type: "Java · Game development", image: "/projects/byow.png", link: "https://sp25.datastructur.es/projects/proj3/", copy: "A procedurally generated 2D tile-based game with player movement, collision handling, and interactive game-state systems.", tags: ["Java", "Data Structures", "2D Game"] },
  { title: "Ants vs. Some Bees", date: "Oct 2025", type: "Python · Game development", image: "/projects/ants.png", link: "https://cs61a.org/proj/ants/", copy: "A strategy tower-defense game built with Python and the UC Berkeley CS 61A teaching framework.", tags: ["Python", "OOP"] },
  { title: "Raspberry Pi Sense HAT Visualization", date: "Feb 2025", type: "MATLAB · Hardware", image: "/projects/raspberry-pi.png", link: "https://github.com/sammydyx/Raspberry-Pi-Visualization/blob/main/Epic%20Quest2%20.pptx", copy: "A MATLAB-to-hardware visualization pipeline that converts image data into an 8 × 8 × 3 RGB display on a Raspberry Pi Sense HAT.", tags: ["Raspberry Pi", "MATLAB"] },
  { title: "Structural Temperature Regulation Cost Analysis", date: "Feb 2025", type: "MATLAB · Energy analysis", image: "/projects/temperature.png", link: "https://github.com/sammydyx/Impact-of-Structural-Design-on-Temperature-Regulation-Costs/blob/main/matlab%20epic%20quest%203%20Poster.pptx.pdf", copy: "A data-driven study of insulation designs, heat transfer, yearly energy use, and temperature-regulation costs.", tags: ["MATLAB", "Data Analysis", "Curve Fitting", "Energy Modeling"] },
  { title: "Vehicle Performance Analysis with OBD-II Data", date: "Jan 2025", type: "MATLAB · Data modeling", image: "/projects/obd.png", link: "https://github.com/sammydyx/OBD-II-HONDA-ACCORD-performance/blob/main/Final_report_Team_Apollo_13.pdf", copy: "A MATLAB system using OBD-II sensor data to model speed, acceleration, engine RPM, and fuel consumption.", tags: ["MATLAB", "OBD-II", "Regression", "Curve Fitting"] },
];

export default function Home() {
  return <main className="site-shell">
    <aside className="sidebar"><a href="#top" className="avatar" aria-label="Yingxin Deng, back to top"><img src="/profile.jpg" alt="Yingxin Deng" /></a><h1>Yingxin (Sammy) Deng</h1><p className="role">Statistics + CS @ UC Berkeley</p><section className="side-about" id="about"><p>I’m a senior at UC Berkeley studying Statistics with a minor in Computer Science. This is where design meets code.</p></section><section className="side-contact" id="contact"><div><a aria-label="Email Yingxin" href="mailto:sammydyx@berkeley.edu"><img src="https://cdn.simpleicons.org/gmail/F9F7F0" alt="" /></a><a aria-label="GitHub profile" href="https://github.com/sammydyx" target="_blank" rel="noreferrer"><img src="https://cdn.simpleicons.org/github/F9F7F0" alt="" /></a><a aria-label="LinkedIn profile" href="https://www.linkedin.com/in/sammy-deng-415637255" target="_blank" rel="noreferrer"><span className="linkedin-mark" aria-hidden="true">in</span></a></div></section></aside>
    <section className="content" id="top"><header className="intro-card"><div className="intro-copy"><p className="eyebrow">PORTFOLIO · 2026</p><h2>Hey, I&apos;m Sammy.</h2><p>Welcome to my creative space, where design meets code. I build thoughtful products, data-driven tools, and playful interactive experiences.</p><a href="#work">Explore projects <span>↓</span></a></div></header><section className="projects" id="work"><div className="section-title"><h2>Projects</h2><p>Selected work, 2025–present</p></div><div className="project-grid">{projects.map((project) => <a className="project-card" key={project.title} href={project.link} target="_blank" rel="noreferrer" aria-label={`Open ${project.title}`}>{project.preview === "agent" ? <div className="agent-preview" aria-label="AI agent monitoring dashboard preview"><span>LIVE OBSERVABILITY</span><strong>AI Agent<br />Monitoring</strong><i /><i /><i /></div> : project.preview === "property" ? <div className="property-preview" aria-label="California home price prediction preview"><span>CALIFORNIA · ML MODEL</span><strong>Home price<br />prediction</strong><i /><b>$</b></div> : <img src={project.image} alt={project.title + " project preview"} style={{ width: "100%", height: "235px", display: "block", objectFit: "contain", background: "#f4f1ea" }} />}<div className="project-info"><p className="project-date">{project.date} · {project.type}</p><h3>{project.title}</h3><p>{project.copy}</p><ul className="project-tags">{project.tags.map((tag) => <li key={tag}>{tag}</li>)}</ul></div></a>)}</div></section><footer>© 2026 Yingxin Deng <span>Designed with curiosity.</span></footer></section>
  </main>;
}
